### ISSUE TITLE
Debounce of d3Chart does not debounce

### ISSUE THREAD

**Issue by jfarseneau** [WealthBar/a2d3#12]
In the D3Chart redraw() method, there is a timeout meant to be used as a debounce, but it will instead spawn more timeouts to be run later.

<pre>
this._timeout = setTimeout(() => {
      this.elements.forEach((e) => { e.redraw() })
      this._timeout = null
    }, this.debounce)
</pre>

**Comment by chrisnicola** [comment]
We now have a better way to do this. 🎉
